name = "new-api-docs-v1"
main = ".open-next/worker.js"
compatibility_date = "2026-02-23"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"
